// <auto-generated />
using System;
using CashFlowMvc.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashFlowMvc.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230306131531_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CashFlowMvc.Domain.Entities.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 3, 6, 13, 15, 31, 122, DateTimeKind.Utc).AddTicks(9086),
                            Description = "George Wells Company",
                            PaymentMethodId = 1,
                            Value = 3015.17m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 3, 6, 13, 15, 31, 122, DateTimeKind.Utc).AddTicks(9089),
                            Description = "Mayden Market",
                            PaymentMethodId = 2,
                            Value = 183.25m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 3, 6, 13, 15, 31, 122, DateTimeKind.Utc).AddTicks(9090),
                            Description = "Clean Services S/A",
                            PaymentMethodId = 2,
                            Value = 15850.13m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 3, 6, 13, 15, 31, 122, DateTimeKind.Utc).AddTicks(9091),
                            Description = "Paul Walker Acessories",
                            PaymentMethodId = 1,
                            Value = 11012.33m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 3, 6, 13, 15, 31, 122, DateTimeKind.Utc).AddTicks(9092),
                            Description = "Mindnith Events",
                            PaymentMethodId = 1,
                            Value = 5489.85m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 3, 6, 13, 15, 31, 122, DateTimeKind.Utc).AddTicks(9093),
                            Description = "Energy Company",
                            PaymentMethodId = 2,
                            Value = 2123.74m
                        });
                });

            modelBuilder.Entity("CashFlowMvc.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("DirectionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "inflow exemple",
                            DirectionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "outflow exemple",
                            DirectionId = 2
                        });
                });

            modelBuilder.Entity("CashFlowMvc.Domain.Entities.Operation", b =>
                {
                    b.HasOne("CashFlowMvc.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Operations")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("CashFlowMvc.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
